experiment:
    id: experiment_id
    seed: 6492

##Data
data:
    name: 'pb' # either "pb" or "map"
    maps: "./samples/maps/field.png"
    map_out_name: "./results/map_rgb.png"
    root_dir: "./samples/network"

##Training
train:
    n_gpus: 1
    workers: 0
    max_epoch: 100
    batch_size: 4
    overfit: False

##Network
model:
    num_classes: 4
    pre-trained: False
    lr: 0.01
    loss:
        kl_div_anneal_epochs: 25

simulator:
    path_to_orthomosaic: None
    resize_flag: false
    resize_factor: 1 # ratio to original tile
    gsd: 0.001 # original tile has 11664 x 8750 with 0.001 meter/pixel gsd
    world_range: [2266, 8750] # [w, h] pixel
    sensor:
        resolution: [1024, 1024] # [w, h] pixel
        angle: [45, 45] # [w, h] degree

mapper:
  poses: [3, 8]
  map_boundary: [2266, 8750] # [w, h] pixel
  ground_resolution: [0.001, 0.001] # [0.001, 0.001]
  class_number: 4
